version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
  app:
    image: bloglist-front-dev
    build:
      context: ./bloglist-frontend
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./bloglist-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: bloglist-front-dev # This will name the container hello-front-dev
    environment:
      - REACT_APP_BACKEND_URL=//localhost:3001
  server:
    image: bloglist-back-dev
    build:
      context: ./bloglist-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
    ports:
      - 3001:3001
    container_name: blog-back-dev
    environment:
      - MONGO_URL=mongodb://joel:kotka09@my-app_mongo_1/blog
      - PORT=3001
      - SECRET=sekred
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: joel
      MONGO_INITDB_ROOT_PASSWORD: kotka09
      MONGO_INITDB_DATABASE: blog
    volumes:
      - ./bloglist-backend/mongo_data:/data/db
